"""
Script to update main commands/__init__.py and queries/__init__.py
"""

from pathlib import Path

BASE_DIR = Path(__file__).parent.parent

def update_main_commands_init():
    """Update main commands __init__.py"""
    init_file = BASE_DIR / 'application' / 'commands' / '__init__.py'
    
    content = '''from .users import (
    CreateUserCommand, CreateUserHandler,
    UpdateUserCommand, UpdateUserHandler,
    DeleteUserCommand, DeleteUserHandler,
)
from .projects import (
    CreateProjectCommand, CreateProjectHandler,
    UpdateProjectCommand, UpdateProjectHandler,
    DeleteProjectCommand, DeleteProjectHandler,
)
from .banking import (
    CreateBankAccountCommand, CreateBankAccountHandler,
    UpdateBankAccountCommand, UpdateBankAccountHandler,
    DeleteBankAccountCommand, DeleteBankAccountHandler,
    CreateTillCommand, CreateTillHandler,
    UpdateTillCommand, UpdateTillHandler,
    DeleteTillCommand, DeleteTillHandler,
    CreateBankTransactionCommand, CreateBankTransactionHandler,
    UpdateBankTransactionCommand, UpdateBankTransactionHandler,
    DeleteBankTransactionCommand, DeleteBankTransactionHandler,
    CreateTillTransactionCommand, CreateTillTransactionHandler,
    UpdateTillTransactionCommand, UpdateTillTransactionHandler,
    DeleteTillTransactionCommand, DeleteTillTransactionHandler,
)
from .crm import (
    CreateCustomerCommand, CreateCustomerHandler,
    UpdateCustomerCommand, UpdateCustomerHandler,
    DeleteCustomerCommand, DeleteCustomerHandler,
    CreateLeadCommand, CreateLeadHandler,
    UpdateLeadCommand, UpdateLeadHandler,
    DeleteLeadCommand, DeleteLeadHandler,
    CreateContactCommand, CreateContactHandler,
    UpdateContactCommand, UpdateContactHandler,
    DeleteContactCommand, DeleteContactHandler,
    CreateCompanyCommand, CreateCompanyHandler,
    UpdateCompanyCommand, UpdateCompanyHandler,
    DeleteCompanyCommand, DeleteCompanyHandler,
    CreateOpportunityCommand, CreateOpportunityHandler,
    UpdateOpportunityCommand, UpdateOpportunityHandler,
    DeleteOpportunityCommand, DeleteOpportunityHandler,
    CreateSalesActivityCommand, CreateSalesActivityHandler,
    UpdateSalesActivityCommand, UpdateSalesActivityHandler,
    DeleteSalesActivityCommand, DeleteSalesActivityHandler,
)
from .hrm import (
    CreateEmployeeCommand, CreateEmployeeHandler,
    UpdateEmployeeCommand, UpdateEmployeeHandler,
    DeleteEmployeeCommand, DeleteEmployeeHandler,
    CreateJobPostingCommand, CreateJobPostingHandler,
    UpdateJobPostingCommand, UpdateJobPostingHandler,
    DeleteJobPostingCommand, DeleteJobPostingHandler,
    CreateApplicationCommand, CreateApplicationHandler,
    UpdateApplicationCommand, UpdateApplicationHandler,
    DeleteApplicationCommand, DeleteApplicationHandler,
    CreatePerformanceReviewCommand, CreatePerformanceReviewHandler,
    UpdatePerformanceReviewCommand, UpdatePerformanceReviewHandler,
    DeletePerformanceReviewCommand, DeletePerformanceReviewHandler,
    CreateTimeEntryCommand, CreateTimeEntryHandler,
    UpdateTimeEntryCommand, UpdateTimeEntryHandler,
    DeleteTimeEntryCommand, DeleteTimeEntryHandler,
    CreateLeaveRequestCommand, CreateLeaveRequestHandler,
    UpdateLeaveRequestCommand, UpdateLeaveRequestHandler,
    DeleteLeaveRequestCommand, DeleteLeaveRequestHandler,
    CreatePayrollCommand, CreatePayrollHandler,
    UpdatePayrollCommand, UpdatePayrollHandler,
    DeletePayrollCommand, DeletePayrollHandler,
    CreateBenefitsCommand, CreateBenefitsHandler,
    UpdateBenefitsCommand, UpdateBenefitsHandler,
    DeleteBenefitsCommand, DeleteBenefitsHandler,
    CreateTrainingCommand, CreateTrainingHandler,
    UpdateTrainingCommand, UpdateTrainingHandler,
    DeleteTrainingCommand, DeleteTrainingHandler,
    CreateTrainingEnrollmentCommand, CreateTrainingEnrollmentHandler,
    UpdateTrainingEnrollmentCommand, UpdateTrainingEnrollmentHandler,
    DeleteTrainingEnrollmentCommand, DeleteTrainingEnrollmentHandler,
    CreateSupplierCommand, CreateSupplierHandler,
    UpdateSupplierCommand, UpdateSupplierHandler,
    DeleteSupplierCommand, DeleteSupplierHandler,
)
from .inventory import (
    CreateProductCommand, CreateProductHandler,
    UpdateProductCommand, UpdateProductHandler,
    DeleteProductCommand, DeleteProductHandler,
    CreateWarehouseCommand, CreateWarehouseHandler,
    UpdateWarehouseCommand, UpdateWarehouseHandler,
    DeleteWarehouseCommand, DeleteWarehouseHandler,
    CreatePurchaseOrderCommand, CreatePurchaseOrderHandler,
    UpdatePurchaseOrderCommand, UpdatePurchaseOrderHandler,
    DeletePurchaseOrderCommand, DeletePurchaseOrderHandler,
    CreateReceivingCommand, CreateReceivingHandler,
    UpdateReceivingCommand, UpdateReceivingHandler,
    DeleteReceivingCommand, DeleteReceivingHandler,
    CreateStorageLocationCommand, CreateStorageLocationHandler,
    UpdateStorageLocationCommand, UpdateStorageLocationHandler,
    DeleteStorageLocationCommand, DeleteStorageLocationHandler,
    CreateStockMovementCommand, CreateStockMovementHandler,
    UpdateStockMovementCommand, UpdateStockMovementHandler,
    DeleteStockMovementCommand, DeleteStockMovementHandler,
)
from .ledger import (
    CreateChartOfAccountsCommand, CreateChartOfAccountsHandler,
    UpdateChartOfAccountsCommand, UpdateChartOfAccountsHandler,
    DeleteChartOfAccountsCommand, DeleteChartOfAccountsHandler,
    CreateJournalEntryCommand, CreateJournalEntryHandler,
    UpdateJournalEntryCommand, UpdateJournalEntryHandler,
    DeleteJournalEntryCommand, DeleteJournalEntryHandler,
    CreateLedgerTransactionCommand, CreateLedgerTransactionHandler,
    UpdateLedgerTransactionCommand, UpdateLedgerTransactionHandler,
    DeleteLedgerTransactionCommand, DeleteLedgerTransactionHandler,
    CreateFinancialPeriodCommand, CreateFinancialPeriodHandler,
    UpdateFinancialPeriodCommand, UpdateFinancialPeriodHandler,
    DeleteFinancialPeriodCommand, DeleteFinancialPeriodHandler,
    CreateBudgetCommand, CreateBudgetHandler,
    UpdateBudgetCommand, UpdateBudgetHandler,
    DeleteBudgetCommand, DeleteBudgetHandler,
    CreateBudgetItemCommand, CreateBudgetItemHandler,
    UpdateBudgetItemCommand, UpdateBudgetItemHandler,
    DeleteBudgetItemCommand, DeleteBudgetItemHandler,
    CreateAccountReceivableCommand, CreateAccountReceivableHandler,
    UpdateAccountReceivableCommand, UpdateAccountReceivableHandler,
    DeleteAccountReceivableCommand, DeleteAccountReceivableHandler,
)
from .invoice import (
    CreateInvoiceCommand, CreateInvoiceHandler,
    UpdateInvoiceCommand, UpdateInvoiceHandler,
    DeleteInvoiceCommand, DeleteInvoiceHandler,
    CreatePaymentCommand, CreatePaymentHandler,
    UpdatePaymentCommand, UpdatePaymentHandler,
    DeletePaymentCommand, DeletePaymentHandler,
)
from .sales import (
    CreateQuoteCommand, CreateQuoteHandler,
    UpdateQuoteCommand, UpdateQuoteHandler,
    DeleteQuoteCommand, DeleteQuoteHandler,
    CreateContractCommand, CreateContractHandler,
    UpdateContractCommand, UpdateContractHandler,
    DeleteContractCommand, DeleteContractHandler,
)
from .pos import (
    CreatePOSShiftCommand, CreatePOSShiftHandler,
    UpdatePOSShiftCommand, UpdatePOSShiftHandler,
    DeletePOSShiftCommand, DeletePOSShiftHandler,
    CreatePOSTransactionCommand, CreatePOSTransactionHandler,
    UpdatePOSTransactionCommand, UpdatePOSTransactionHandler,
    DeletePOSTransactionCommand, DeletePOSTransactionHandler,
)
from .workshop import (
    CreateWorkOrderCommand, CreateWorkOrderHandler,
    UpdateWorkOrderCommand, UpdateWorkOrderHandler,
    DeleteWorkOrderCommand, DeleteWorkOrderHandler,
    CreateWorkOrderTaskCommand, CreateWorkOrderTaskHandler,
    UpdateWorkOrderTaskCommand, UpdateWorkOrderTaskHandler,
    DeleteWorkOrderTaskCommand, DeleteWorkOrderTaskHandler,
)
from .production import (
    CreateProductionPlanCommand, CreateProductionPlanHandler,
    UpdateProductionPlanCommand, UpdateProductionPlanHandler,
    DeleteProductionPlanCommand, DeleteProductionPlanHandler,
    CreateProductionStepCommand, CreateProductionStepHandler,
    UpdateProductionStepCommand, UpdateProductionStepHandler,
    DeleteProductionStepCommand, DeleteProductionStepHandler,
    CreateProductionScheduleCommand, CreateProductionScheduleHandler,
    UpdateProductionScheduleCommand, UpdateProductionScheduleHandler,
    DeleteProductionScheduleCommand, DeleteProductionScheduleHandler,
)
from .event import (
    CreateEventCommand, CreateEventHandler,
    UpdateEventCommand, UpdateEventHandler,
    DeleteEventCommand, DeleteEventHandler,
)
from .quality_control import (
    CreateQualityCheckCommand, CreateQualityCheckHandler,
    UpdateQualityCheckCommand, UpdateQualityCheckHandler,
    DeleteQualityCheckCommand, DeleteQualityCheckHandler,
    CreateQualityInspectionCommand, CreateQualityInspectionHandler,
    UpdateQualityInspectionCommand, UpdateQualityInspectionHandler,
    DeleteQualityInspectionCommand, DeleteQualityInspectionHandler,
    CreateQualityDefectCommand, CreateQualityDefectHandler,
    UpdateQualityDefectCommand, UpdateQualityDefectHandler,
    DeleteQualityDefectCommand, DeleteQualityDefectHandler,
    CreateQualityReportCommand, CreateQualityReportHandler,
    UpdateQualityReportCommand, UpdateQualityReportHandler,
    DeleteQualityReportCommand, DeleteQualityReportHandler,
)
from .maintenance import (
    CreateMaintenanceScheduleCommand, CreateMaintenanceScheduleHandler,
    UpdateMaintenanceScheduleCommand, UpdateMaintenanceScheduleHandler,
    DeleteMaintenanceScheduleCommand, DeleteMaintenanceScheduleHandler,
    CreateMaintenanceWorkOrderCommand, CreateMaintenanceWorkOrderHandler,
    UpdateMaintenanceWorkOrderCommand, UpdateMaintenanceWorkOrderHandler,
    DeleteMaintenanceWorkOrderCommand, DeleteMaintenanceWorkOrderHandler,
    CreateEquipmentCommand, CreateEquipmentHandler,
    UpdateEquipmentCommand, UpdateEquipmentHandler,
    DeleteEquipmentCommand, DeleteEquipmentHandler,
    CreateMaintenanceReportCommand, CreateMaintenanceReportHandler,
    UpdateMaintenanceReportCommand, UpdateMaintenanceReportHandler,
    DeleteMaintenanceReportCommand, DeleteMaintenanceReportHandler,
)
from .investment import (
    CreateInvestmentCommand, CreateInvestmentHandler,
    UpdateInvestmentCommand, UpdateInvestmentHandler,
    DeleteInvestmentCommand, DeleteInvestmentHandler,
    CreateEquipmentInvestmentCommand, CreateEquipmentInvestmentHandler,
    UpdateEquipmentInvestmentCommand, UpdateEquipmentInvestmentHandler,
    DeleteEquipmentInvestmentCommand, DeleteEquipmentInvestmentHandler,
    CreateInvestmentTransactionCommand, CreateInvestmentTransactionHandler,
    UpdateInvestmentTransactionCommand, UpdateInvestmentTransactionHandler,
    DeleteInvestmentTransactionCommand, DeleteInvestmentTransactionHandler,
)
from .core import (
    CreateRoleCommand, CreateRoleHandler,
    UpdateRoleCommand, UpdateRoleHandler,
    DeleteRoleCommand, DeleteRoleHandler,
    CreateTenantUserCommand, CreateTenantUserHandler,
    UpdateTenantUserCommand, UpdateTenantUserHandler,
    DeleteTenantUserCommand, DeleteTenantUserHandler,
)
from .notification import (
    CreateNotificationCommand, CreateNotificationHandler,
    UpdateNotificationCommand, UpdateNotificationHandler,
    DeleteNotificationCommand, DeleteNotificationHandler,
    CreateNotificationPreferenceCommand, CreateNotificationPreferenceHandler,
    UpdateNotificationPreferenceCommand, UpdateNotificationPreferenceHandler,
    DeleteNotificationPreferenceCommand, DeleteNotificationPreferenceHandler,
)
from .invoice_customization import (
    CreateInvoiceCustomizationCommand, CreateInvoiceCustomizationHandler,
    UpdateInvoiceCustomizationCommand, UpdateInvoiceCustomizationHandler,
    DeleteInvoiceCustomizationCommand, DeleteInvoiceCustomizationHandler,
)

__all__ = [
    'CreateUserCommand', 'CreateUserHandler',
    'UpdateUserCommand', 'UpdateUserHandler',
    'DeleteUserCommand', 'DeleteUserHandler',
    'CreateProjectCommand', 'CreateProjectHandler',
    'UpdateProjectCommand', 'UpdateProjectHandler',
    'DeleteProjectCommand', 'DeleteProjectHandler',
    'CreateBankAccountCommand', 'CreateBankAccountHandler',
    'UpdateBankAccountCommand', 'UpdateBankAccountHandler',
    'DeleteBankAccountCommand', 'DeleteBankAccountHandler',
    'CreateTillCommand', 'CreateTillHandler',
    'UpdateTillCommand', 'UpdateTillHandler',
    'DeleteTillCommand', 'DeleteTillHandler',
    'CreateBankTransactionCommand', 'CreateBankTransactionHandler',
    'UpdateBankTransactionCommand', 'UpdateBankTransactionHandler',
    'DeleteBankTransactionCommand', 'DeleteBankTransactionHandler',
    'CreateTillTransactionCommand', 'CreateTillTransactionHandler',
    'UpdateTillTransactionCommand', 'UpdateTillTransactionHandler',
    'DeleteTillTransactionCommand', 'DeleteTillTransactionHandler',
    'CreateCustomerCommand', 'CreateCustomerHandler',
    'UpdateCustomerCommand', 'UpdateCustomerHandler',
    'DeleteCustomerCommand', 'DeleteCustomerHandler',
    'CreateLeadCommand', 'CreateLeadHandler',
    'UpdateLeadCommand', 'UpdateLeadHandler',
    'DeleteLeadCommand', 'DeleteLeadHandler',
    'CreateContactCommand', 'CreateContactHandler',
    'UpdateContactCommand', 'UpdateContactHandler',
    'DeleteContactCommand', 'DeleteContactHandler',
    'CreateCompanyCommand', 'CreateCompanyHandler',
    'UpdateCompanyCommand', 'UpdateCompanyHandler',
    'DeleteCompanyCommand', 'DeleteCompanyHandler',
    'CreateOpportunityCommand', 'CreateOpportunityHandler',
    'UpdateOpportunityCommand', 'UpdateOpportunityHandler',
    'DeleteOpportunityCommand', 'DeleteOpportunityHandler',
    'CreateSalesActivityCommand', 'CreateSalesActivityHandler',
    'UpdateSalesActivityCommand', 'UpdateSalesActivityHandler',
    'DeleteSalesActivityCommand', 'DeleteSalesActivityHandler',
    'CreateEmployeeCommand', 'CreateEmployeeHandler',
    'UpdateEmployeeCommand', 'UpdateEmployeeHandler',
    'DeleteEmployeeCommand', 'DeleteEmployeeHandler',
    'CreateJobPostingCommand', 'CreateJobPostingHandler',
    'UpdateJobPostingCommand', 'UpdateJobPostingHandler',
    'DeleteJobPostingCommand', 'DeleteJobPostingHandler',
    'CreateApplicationCommand', 'CreateApplicationHandler',
    'UpdateApplicationCommand', 'UpdateApplicationHandler',
    'DeleteApplicationCommand', 'DeleteApplicationHandler',
    'CreatePerformanceReviewCommand', 'CreatePerformanceReviewHandler',
    'UpdatePerformanceReviewCommand', 'UpdatePerformanceReviewHandler',
    'DeletePerformanceReviewCommand', 'DeletePerformanceReviewHandler',
    'CreateTimeEntryCommand', 'CreateTimeEntryHandler',
    'UpdateTimeEntryCommand', 'UpdateTimeEntryHandler',
    'DeleteTimeEntryCommand', 'DeleteTimeEntryHandler',
    'CreateLeaveRequestCommand', 'CreateLeaveRequestHandler',
    'UpdateLeaveRequestCommand', 'UpdateLeaveRequestHandler',
    'DeleteLeaveRequestCommand', 'DeleteLeaveRequestHandler',
    'CreatePayrollCommand', 'CreatePayrollHandler',
    'UpdatePayrollCommand', 'UpdatePayrollHandler',
    'DeletePayrollCommand', 'DeletePayrollHandler',
    'CreateBenefitsCommand', 'CreateBenefitsHandler',
    'UpdateBenefitsCommand', 'UpdateBenefitsHandler',
    'DeleteBenefitsCommand', 'DeleteBenefitsHandler',
    'CreateTrainingCommand', 'CreateTrainingHandler',
    'UpdateTrainingCommand', 'UpdateTrainingHandler',
    'DeleteTrainingCommand', 'DeleteTrainingHandler',
    'CreateTrainingEnrollmentCommand', 'CreateTrainingEnrollmentHandler',
    'UpdateTrainingEnrollmentCommand', 'UpdateTrainingEnrollmentHandler',
    'DeleteTrainingEnrollmentCommand', 'DeleteTrainingEnrollmentHandler',
    'CreateSupplierCommand', 'CreateSupplierHandler',
    'UpdateSupplierCommand', 'UpdateSupplierHandler',
    'DeleteSupplierCommand', 'DeleteSupplierHandler',
    'CreateProductCommand', 'CreateProductHandler',
    'UpdateProductCommand', 'UpdateProductHandler',
    'DeleteProductCommand', 'DeleteProductHandler',
    'CreateWarehouseCommand', 'CreateWarehouseHandler',
    'UpdateWarehouseCommand', 'UpdateWarehouseHandler',
    'DeleteWarehouseCommand', 'DeleteWarehouseHandler',
    'CreatePurchaseOrderCommand', 'CreatePurchaseOrderHandler',
    'UpdatePurchaseOrderCommand', 'UpdatePurchaseOrderHandler',
    'DeletePurchaseOrderCommand', 'DeletePurchaseOrderHandler',
    'CreateReceivingCommand', 'CreateReceivingHandler',
    'UpdateReceivingCommand', 'UpdateReceivingHandler',
    'DeleteReceivingCommand', 'DeleteReceivingHandler',
    'CreateStorageLocationCommand', 'CreateStorageLocationHandler',
    'UpdateStorageLocationCommand', 'UpdateStorageLocationHandler',
    'DeleteStorageLocationCommand', 'DeleteStorageLocationHandler',
    'CreateStockMovementCommand', 'CreateStockMovementHandler',
    'UpdateStockMovementCommand', 'UpdateStockMovementHandler',
    'DeleteStockMovementCommand', 'DeleteStockMovementHandler',
    'CreateChartOfAccountsCommand', 'CreateChartOfAccountsHandler',
    'UpdateChartOfAccountsCommand', 'UpdateChartOfAccountsHandler',
    'DeleteChartOfAccountsCommand', 'DeleteChartOfAccountsHandler',
    'CreateJournalEntryCommand', 'CreateJournalEntryHandler',
    'UpdateJournalEntryCommand', 'UpdateJournalEntryHandler',
    'DeleteJournalEntryCommand', 'DeleteJournalEntryHandler',
    'CreateLedgerTransactionCommand', 'CreateLedgerTransactionHandler',
    'UpdateLedgerTransactionCommand', 'UpdateLedgerTransactionHandler',
    'DeleteLedgerTransactionCommand', 'DeleteLedgerTransactionHandler',
    'CreateFinancialPeriodCommand', 'CreateFinancialPeriodHandler',
    'UpdateFinancialPeriodCommand', 'UpdateFinancialPeriodHandler',
    'DeleteFinancialPeriodCommand', 'DeleteFinancialPeriodHandler',
    'CreateBudgetCommand', 'CreateBudgetHandler',
    'UpdateBudgetCommand', 'UpdateBudgetHandler',
    'DeleteBudgetCommand', 'DeleteBudgetHandler',
    'CreateBudgetItemCommand', 'CreateBudgetItemHandler',
    'UpdateBudgetItemCommand', 'UpdateBudgetItemHandler',
    'DeleteBudgetItemCommand', 'DeleteBudgetItemHandler',
    'CreateAccountReceivableCommand', 'CreateAccountReceivableHandler',
    'UpdateAccountReceivableCommand', 'UpdateAccountReceivableHandler',
    'DeleteAccountReceivableCommand', 'DeleteAccountReceivableHandler',
    'CreateInvoiceCommand', 'CreateInvoiceHandler',
    'UpdateInvoiceCommand', 'UpdateInvoiceHandler',
    'DeleteInvoiceCommand', 'DeleteInvoiceHandler',
    'CreatePaymentCommand', 'CreatePaymentHandler',
    'UpdatePaymentCommand', 'UpdatePaymentHandler',
    'DeletePaymentCommand', 'DeletePaymentHandler',
    'CreateQuoteCommand', 'CreateQuoteHandler',
    'UpdateQuoteCommand', 'UpdateQuoteHandler',
    'DeleteQuoteCommand', 'DeleteQuoteHandler',
    'CreateContractCommand', 'CreateContractHandler',
    'UpdateContractCommand', 'UpdateContractHandler',
    'DeleteContractCommand', 'DeleteContractHandler',
    'CreatePOSShiftCommand', 'CreatePOSShiftHandler',
    'UpdatePOSShiftCommand', 'UpdatePOSShiftHandler',
    'DeletePOSShiftCommand', 'DeletePOSShiftHandler',
    'CreatePOSTransactionCommand', 'CreatePOSTransactionHandler',
    'UpdatePOSTransactionCommand', 'UpdatePOSTransactionHandler',
    'DeletePOSTransactionCommand', 'DeletePOSTransactionHandler',
    'CreateWorkOrderCommand', 'CreateWorkOrderHandler',
    'UpdateWorkOrderCommand', 'UpdateWorkOrderHandler',
    'DeleteWorkOrderCommand', 'DeleteWorkOrderHandler',
    'CreateWorkOrderTaskCommand', 'CreateWorkOrderTaskHandler',
    'UpdateWorkOrderTaskCommand', 'UpdateWorkOrderTaskHandler',
    'DeleteWorkOrderTaskCommand', 'DeleteWorkOrderTaskHandler',
    'CreateProductionPlanCommand', 'CreateProductionPlanHandler',
    'UpdateProductionPlanCommand', 'UpdateProductionPlanHandler',
    'DeleteProductionPlanCommand', 'DeleteProductionPlanHandler',
    'CreateProductionStepCommand', 'CreateProductionStepHandler',
    'UpdateProductionStepCommand', 'UpdateProductionStepHandler',
    'DeleteProductionStepCommand', 'DeleteProductionStepHandler',
    'CreateProductionScheduleCommand', 'CreateProductionScheduleHandler',
    'UpdateProductionScheduleCommand', 'UpdateProductionScheduleHandler',
    'DeleteProductionScheduleCommand', 'DeleteProductionScheduleHandler',
    'CreateEventCommand', 'CreateEventHandler',
    'UpdateEventCommand', 'UpdateEventHandler',
    'DeleteEventCommand', 'DeleteEventHandler',
    'CreateQualityCheckCommand', 'CreateQualityCheckHandler',
    'UpdateQualityCheckCommand', 'UpdateQualityCheckHandler',
    'DeleteQualityCheckCommand', 'DeleteQualityCheckHandler',
    'CreateQualityInspectionCommand', 'CreateQualityInspectionHandler',
    'UpdateQualityInspectionCommand', 'UpdateQualityInspectionHandler',
    'DeleteQualityInspectionCommand', 'DeleteQualityInspectionHandler',
    'CreateQualityDefectCommand', 'CreateQualityDefectHandler',
    'UpdateQualityDefectCommand', 'UpdateQualityDefectHandler',
    'DeleteQualityDefectCommand', 'DeleteQualityDefectHandler',
    'CreateQualityReportCommand', 'CreateQualityReportHandler',
    'UpdateQualityReportCommand', 'UpdateQualityReportHandler',
    'DeleteQualityReportCommand', 'DeleteQualityReportHandler',
    'CreateMaintenanceScheduleCommand', 'CreateMaintenanceScheduleHandler',
    'UpdateMaintenanceScheduleCommand', 'UpdateMaintenanceScheduleHandler',
    'DeleteMaintenanceScheduleCommand', 'DeleteMaintenanceScheduleHandler',
    'CreateMaintenanceWorkOrderCommand', 'CreateMaintenanceWorkOrderHandler',
    'UpdateMaintenanceWorkOrderCommand', 'UpdateMaintenanceWorkOrderHandler',
    'DeleteMaintenanceWorkOrderCommand', 'DeleteMaintenanceWorkOrderHandler',
    'CreateEquipmentCommand', 'CreateEquipmentHandler',
    'UpdateEquipmentCommand', 'UpdateEquipmentHandler',
    'DeleteEquipmentCommand', 'DeleteEquipmentHandler',
    'CreateMaintenanceReportCommand', 'CreateMaintenanceReportHandler',
    'UpdateMaintenanceReportCommand', 'UpdateMaintenanceReportHandler',
    'DeleteMaintenanceReportCommand', 'DeleteMaintenanceReportHandler',
    'CreateInvestmentCommand', 'CreateInvestmentHandler',
    'UpdateInvestmentCommand', 'UpdateInvestmentHandler',
    'DeleteInvestmentCommand', 'DeleteInvestmentHandler',
    'CreateEquipmentInvestmentCommand', 'CreateEquipmentInvestmentHandler',
    'UpdateEquipmentInvestmentCommand', 'UpdateEquipmentInvestmentHandler',
    'DeleteEquipmentInvestmentCommand', 'DeleteEquipmentInvestmentHandler',
    'CreateInvestmentTransactionCommand', 'CreateInvestmentTransactionHandler',
    'UpdateInvestmentTransactionCommand', 'UpdateInvestmentTransactionHandler',
    'DeleteInvestmentTransactionCommand', 'DeleteInvestmentTransactionHandler',
    'CreateRoleCommand', 'CreateRoleHandler',
    'UpdateRoleCommand', 'UpdateRoleHandler',
    'DeleteRoleCommand', 'DeleteRoleHandler',
    'CreateTenantUserCommand', 'CreateTenantUserHandler',
    'UpdateTenantUserCommand', 'UpdateTenantUserHandler',
    'DeleteTenantUserCommand', 'DeleteTenantUserHandler',
    'CreateNotificationCommand', 'CreateNotificationHandler',
    'UpdateNotificationCommand', 'UpdateNotificationHandler',
    'DeleteNotificationCommand', 'DeleteNotificationHandler',
    'CreateNotificationPreferenceCommand', 'CreateNotificationPreferenceHandler',
    'UpdateNotificationPreferenceCommand', 'UpdateNotificationPreferenceHandler',
    'DeleteNotificationPreferenceCommand', 'DeleteNotificationPreferenceHandler',
    'CreateInvoiceCustomizationCommand', 'CreateInvoiceCustomizationHandler',
    'UpdateInvoiceCustomizationCommand', 'UpdateInvoiceCustomizationHandler',
    'DeleteInvoiceCustomizationCommand', 'DeleteInvoiceCustomizationHandler',
]
'''
    
    with open(init_file, 'w', encoding='utf-8') as f:
        f.write(content)

def update_main_queries_init():
    """Update main queries __init__.py"""
    init_file = BASE_DIR / 'application' / 'queries' / '__init__.py'
    
    content = '''from .users import (
    GetUserByIdQuery, GetUserByIdHandler,
    GetAllUsersQuery, GetAllUsersHandler,
    GetUserByEmailQuery, GetUserByEmailHandler,
)
from .projects import (
    GetProjectByIdQuery, GetProjectByIdHandler,
    GetAllProjectsQuery, GetAllProjectsHandler,
)
from .banking import (
    GetBankAccountByIdQuery, GetBankAccountByIdHandler,
    GetAllBankAccountsQuery, GetAllBankAccountsHandler,
    GetBankTransactionByIdQuery, GetBankTransactionByIdHandler,
    GetAllBankTransactionsQuery, GetAllBankTransactionsHandler,
    GetTillByIdQuery, GetTillByIdHandler,
    GetAllTillsQuery, GetAllTillsHandler,
    GetTillTransactionByIdQuery, GetTillTransactionByIdHandler,
    GetAllTillTransactionsQuery, GetAllTillTransactionsHandler,
)
from .crm import (
    GetCustomerByIdQuery, GetCustomerByIdHandler,
    GetAllCustomersQuery, GetAllCustomersHandler,
    GetLeadByIdQuery, GetLeadByIdHandler,
    GetAllLeadsQuery, GetAllLeadsHandler,
    GetContactByIdQuery, GetContactByIdHandler,
    GetAllContactsQuery, GetAllContactsHandler,
    GetCompanyByIdQuery, GetCompanyByIdHandler,
    GetAllCompaniesQuery, GetAllCompaniesHandler,
    GetOpportunityByIdQuery, GetOpportunityByIdHandler,
    GetAllOpportunitiesQuery, GetAllOpportunitiesHandler,
    GetSalesActivityByIdQuery, GetSalesActivityByIdHandler,
    GetAllSalesActivitiesQuery, GetAllSalesActivitiesHandler,
)
from .hrm import (
    GetEmployeeByIdQuery, GetEmployeeByIdHandler,
    GetAllEmployeesQuery, GetAllEmployeesHandler,
    GetApplicationByIdQuery, GetApplicationByIdHandler,
    GetAllApplicationsQuery, GetAllApplicationsHandler,
    GetPerformanceReviewByIdQuery, GetPerformanceReviewByIdHandler,
    GetAllPerformanceReviewsQuery, GetAllPerformanceReviewsHandler,
    GetTimeEntryByIdQuery, GetTimeEntryByIdHandler,
    GetAllTimeEntriesQuery, GetAllTimeEntriesHandler,
    GetLeaveRequestByIdQuery, GetLeaveRequestByIdHandler,
    GetAllLeaveRequestsQuery, GetAllLeaveRequestsHandler,
    GetPayrollByIdQuery, GetPayrollByIdHandler,
    GetAllPayrollsQuery, GetAllPayrollsHandler,
    GetBenefitsByIdQuery, GetBenefitsByIdHandler,
    GetAllBenefitsQuery, GetAllBenefitsHandler,
    GetTrainingByIdQuery, GetTrainingByIdHandler,
    GetAllTrainingsQuery, GetAllTrainingsHandler,
    GetTrainingEnrollmentByIdQuery, GetTrainingEnrollmentByIdHandler,
    GetAllTrainingEnrollmentsQuery, GetAllTrainingEnrollmentsHandler,
    GetSupplierByIdQuery, GetSupplierByIdHandler,
    GetAllSuppliersQuery, GetAllSuppliersHandler,
)
from .inventory import (
    GetProductByIdQuery, GetProductByIdHandler,
    GetAllProductsQuery, GetAllProductsHandler,
    GetWarehouseByIdQuery, GetWarehouseByIdHandler,
    GetAllWarehousesQuery, GetAllWarehousesHandler,
    GetPurchaseOrderByIdQuery, GetPurchaseOrderByIdHandler,
    GetAllPurchaseOrdersQuery, GetAllPurchaseOrdersHandler,
    GetReceivingByIdQuery, GetReceivingByIdHandler,
    GetAllReceivingsQuery, GetAllReceivingsHandler,
    GetStorageLocationByIdQuery, GetStorageLocationByIdHandler,
    GetAllStorageLocationsQuery, GetAllStorageLocationsHandler,
    GetStockMovementByIdQuery, GetStockMovementByIdHandler,
    GetAllStockMovementsQuery, GetAllStockMovementsHandler,
)
from .ledger import (
    GetChartOfAccountsByIdQuery, GetChartOfAccountsByIdHandler,
    GetAllChartOfAccountssQuery, GetAllChartOfAccountssHandler,
    GetJournalEntryByIdQuery, GetJournalEntryByIdHandler,
    GetAllJournalEntriesQuery, GetAllJournalEntriesHandler,
    GetLedgerTransactionByIdQuery, GetLedgerTransactionByIdHandler,
    GetAllLedgerTransactionsQuery, GetAllLedgerTransactionsHandler,
    GetFinancialPeriodByIdQuery, GetFinancialPeriodByIdHandler,
    GetAllFinancialPeriodsQuery, GetAllFinancialPeriodsHandler,
    GetBudgetByIdQuery, GetBudgetByIdHandler,
    GetAllBudgetsQuery, GetAllBudgetsHandler,
    GetBudgetItemByIdQuery, GetBudgetItemByIdHandler,
    GetAllBudgetItemsQuery, GetAllBudgetItemsHandler,
    GetAccountReceivableByIdQuery, GetAccountReceivableByIdHandler,
    GetAllAccountReceivablesQuery, GetAllAccountReceivablesHandler,
)
from .invoice import (
    GetInvoiceByIdQuery, GetInvoiceByIdHandler,
    GetAllInvoicesQuery, GetAllInvoicesHandler,
    GetPaymentByIdQuery, GetPaymentByIdHandler,
    GetAllPaymentsQuery, GetAllPaymentsHandler,
)
from .sales import (
    GetQuoteByIdQuery, GetQuoteByIdHandler,
    GetAllQuotesQuery, GetAllQuotesHandler,
    GetContractByIdQuery, GetContractByIdHandler,
    GetAllContractsQuery, GetAllContractsHandler,
)
from .pos import (
    GetPOSShiftByIdQuery, GetPOSShiftByIdHandler,
    GetAllPOSShiftsQuery, GetAllPOSShiftsHandler,
    GetPOSTransactionByIdQuery, GetPOSTransactionByIdHandler,
    GetAllPOSTransactionsQuery, GetAllPOSTransactionsHandler,
)
from .workshop import (
    GetWorkOrderByIdQuery, GetWorkOrderByIdHandler,
    GetAllWorkOrdersQuery, GetAllWorkOrdersHandler,
    GetWorkOrderTaskByIdQuery, GetWorkOrderTaskByIdHandler,
    GetAllWorkOrderTasksQuery, GetAllWorkOrderTasksHandler,
)
from .production import (
    GetProductionPlanByIdQuery, GetProductionPlanByIdHandler,
    GetAllProductionPlansQuery, GetAllProductionPlansHandler,
    GetProductionStepByIdQuery, GetProductionStepByIdHandler,
    GetAllProductionStepsQuery, GetAllProductionStepsHandler,
    GetProductionScheduleByIdQuery, GetProductionScheduleByIdHandler,
    GetAllProductionSchedulesQuery, GetAllProductionSchedulesHandler,
)
from .event import (
    GetEventByIdQuery, GetEventByIdHandler,
    GetAllEventsQuery, GetAllEventsHandler,
)
from .quality_control import (
    GetQualityCheckByIdQuery, GetQualityCheckByIdHandler,
    GetAllQualityChecksQuery, GetAllQualityChecksHandler,
    GetQualityInspectionByIdQuery, GetQualityInspectionByIdHandler,
    GetAllQualityInspectionsQuery, GetAllQualityInspectionsHandler,
    GetQualityDefectByIdQuery, GetQualityDefectByIdHandler,
    GetAllQualityDefectsQuery, GetAllQualityDefectsHandler,
    GetQualityReportByIdQuery, GetQualityReportByIdHandler,
    GetAllQualityReportsQuery, GetAllQualityReportsHandler,
)
from .maintenance import (
    GetMaintenanceScheduleByIdQuery, GetMaintenanceScheduleByIdHandler,
    GetAllMaintenanceSchedulesQuery, GetAllMaintenanceSchedulesHandler,
    GetMaintenanceWorkOrderByIdQuery, GetMaintenanceWorkOrderByIdHandler,
    GetAllMaintenanceWorkOrdersQuery, GetAllMaintenanceWorkOrdersHandler,
    GetEquipmentByIdQuery, GetEquipmentByIdHandler,
    GetAllEquipmentsQuery, GetAllEquipmentsHandler,
    GetMaintenanceReportByIdQuery, GetMaintenanceReportByIdHandler,
    GetAllMaintenanceReportsQuery, GetAllMaintenanceReportsHandler,
)
from .investment import (
    GetInvestmentByIdQuery, GetInvestmentByIdHandler,
    GetAllInvestmentsQuery, GetAllInvestmentsHandler,
    GetEquipmentInvestmentByIdQuery, GetEquipmentInvestmentByIdHandler,
    GetAllEquipmentInvestmentsQuery, GetAllEquipmentInvestmentsHandler,
    GetInvestmentTransactionByIdQuery, GetInvestmentTransactionByIdHandler,
    GetAllInvestmentTransactionsQuery, GetAllInvestmentTransactionsHandler,
)
from .core import (
    GetRoleByIdQuery, GetRoleByIdHandler,
    GetAllRolesQuery, GetAllRolesHandler,
    GetTenantUserByIdQuery, GetTenantUserByIdHandler,
    GetAllTenantUsersQuery, GetAllTenantUsersHandler,
)
from .notification import (
    GetNotificationByIdQuery, GetNotificationByIdHandler,
    GetAllNotificationsQuery, GetAllNotificationsHandler,
    GetNotificationPreferenceByIdQuery, GetNotificationPreferenceByIdHandler,
    GetAllNotificationPreferencesQuery, GetAllNotificationPreferencesHandler,
)
from .invoice_customization import (
    GetInvoiceCustomizationByIdQuery, GetInvoiceCustomizationByIdHandler,
    GetAllInvoiceCustomizationsQuery, GetAllInvoiceCustomizationsHandler,
)

__all__ = [
    'GetUserByIdQuery', 'GetUserByIdHandler',
    'GetAllUsersQuery', 'GetAllUsersHandler',
    'GetUserByEmailQuery', 'GetUserByEmailHandler',
    'GetProjectByIdQuery', 'GetProjectByIdHandler',
    'GetAllProjectsQuery', 'GetAllProjectsHandler',
    'GetBankAccountByIdQuery', 'GetBankAccountByIdHandler',
    'GetAllBankAccountsQuery', 'GetAllBankAccountsHandler',
    'GetBankTransactionByIdQuery', 'GetBankTransactionByIdHandler',
    'GetAllBankTransactionsQuery', 'GetAllBankTransactionsHandler',
    'GetTillByIdQuery', 'GetTillByIdHandler',
    'GetAllTillsQuery', 'GetAllTillsHandler',
    'GetTillTransactionByIdQuery', 'GetTillTransactionByIdHandler',
    'GetAllTillTransactionsQuery', 'GetAllTillTransactionsHandler',
    'GetCustomerByIdQuery', 'GetCustomerByIdHandler',
    'GetAllCustomersQuery', 'GetAllCustomersHandler',
    'GetLeadByIdQuery', 'GetLeadByIdHandler',
    'GetAllLeadsQuery', 'GetAllLeadsHandler',
    'GetContactByIdQuery', 'GetContactByIdHandler',
    'GetAllContactsQuery', 'GetAllContactsHandler',
    'GetCompanyByIdQuery', 'GetCompanyByIdHandler',
    'GetAllCompaniesQuery', 'GetAllCompaniesHandler',
    'GetOpportunityByIdQuery', 'GetOpportunityByIdHandler',
    'GetAllOpportunitiesQuery', 'GetAllOpportunitiesHandler',
    'GetSalesActivityByIdQuery', 'GetSalesActivityByIdHandler',
    'GetAllSalesActivitiesQuery', 'GetAllSalesActivitiesHandler',
    'GetEmployeeByIdQuery', 'GetEmployeeByIdHandler',
    'GetAllEmployeesQuery', 'GetAllEmployeesHandler',
    'GetApplicationByIdQuery', 'GetApplicationByIdHandler',
    'GetAllApplicationsQuery', 'GetAllApplicationsHandler',
    'GetPerformanceReviewByIdQuery', 'GetPerformanceReviewByIdHandler',
    'GetAllPerformanceReviewsQuery', 'GetAllPerformanceReviewsHandler',
    'GetTimeEntryByIdQuery', 'GetTimeEntryByIdHandler',
    'GetAllTimeEntriesQuery', 'GetAllTimeEntriesHandler',
    'GetLeaveRequestByIdQuery', 'GetLeaveRequestByIdHandler',
    'GetAllLeaveRequestsQuery', 'GetAllLeaveRequestsHandler',
    'GetPayrollByIdQuery', 'GetPayrollByIdHandler',
    'GetAllPayrollsQuery', 'GetAllPayrollsHandler',
    'GetBenefitsByIdQuery', 'GetBenefitsByIdHandler',
    'GetAllBenefitsQuery', 'GetAllBenefitsHandler',
    'GetTrainingByIdQuery', 'GetTrainingByIdHandler',
    'GetAllTrainingsQuery', 'GetAllTrainingsHandler',
    'GetTrainingEnrollmentByIdQuery', 'GetTrainingEnrollmentByIdHandler',
    'GetAllTrainingEnrollmentsQuery', 'GetAllTrainingEnrollmentsHandler',
    'GetSupplierByIdQuery', 'GetSupplierByIdHandler',
    'GetAllSuppliersQuery', 'GetAllSuppliersHandler',
    'GetProductByIdQuery', 'GetProductByIdHandler',
    'GetAllProductsQuery', 'GetAllProductsHandler',
    'GetWarehouseByIdQuery', 'GetWarehouseByIdHandler',
    'GetAllWarehousesQuery', 'GetAllWarehousesHandler',
    'GetPurchaseOrderByIdQuery', 'GetPurchaseOrderByIdHandler',
    'GetAllPurchaseOrdersQuery', 'GetAllPurchaseOrdersHandler',
    'GetReceivingByIdQuery', 'GetReceivingByIdHandler',
    'GetAllReceivingsQuery', 'GetAllReceivingsHandler',
    'GetStorageLocationByIdQuery', 'GetStorageLocationByIdHandler',
    'GetAllStorageLocationsQuery', 'GetAllStorageLocationsHandler',
    'GetStockMovementByIdQuery', 'GetStockMovementByIdHandler',
    'GetAllStockMovementsQuery', 'GetAllStockMovementsHandler',
    'GetChartOfAccountsByIdQuery', 'GetChartOfAccountsByIdHandler',
    'GetAllChartOfAccountssQuery', 'GetAllChartOfAccountssHandler',
    'GetJournalEntryByIdQuery', 'GetJournalEntryByIdHandler',
    'GetAllJournalEntriesQuery', 'GetAllJournalEntriesHandler',
    'GetLedgerTransactionByIdQuery', 'GetLedgerTransactionByIdHandler',
    'GetAllLedgerTransactionsQuery', 'GetAllLedgerTransactionsHandler',
    'GetFinancialPeriodByIdQuery', 'GetFinancialPeriodByIdHandler',
    'GetAllFinancialPeriodsQuery', 'GetAllFinancialPeriodsHandler',
    'GetBudgetByIdQuery', 'GetBudgetByIdHandler',
    'GetAllBudgetsQuery', 'GetAllBudgetsHandler',
    'GetBudgetItemByIdQuery', 'GetBudgetItemByIdHandler',
    'GetAllBudgetItemsQuery', 'GetAllBudgetItemsHandler',
    'GetAccountReceivableByIdQuery', 'GetAccountReceivableByIdHandler',
    'GetAllAccountReceivablesQuery', 'GetAllAccountReceivablesHandler',
    'GetInvoiceByIdQuery', 'GetInvoiceByIdHandler',
    'GetAllInvoicesQuery', 'GetAllInvoicesHandler',
    'GetPaymentByIdQuery', 'GetPaymentByIdHandler',
    'GetAllPaymentsQuery', 'GetAllPaymentsHandler',
    'GetQuoteByIdQuery', 'GetQuoteByIdHandler',
    'GetAllQuotesQuery', 'GetAllQuotesHandler',
    'GetContractByIdQuery', 'GetContractByIdHandler',
    'GetAllContractsQuery', 'GetAllContractsHandler',
    'GetPOSShiftByIdQuery', 'GetPOSShiftByIdHandler',
    'GetAllPOSShiftsQuery', 'GetAllPOSShiftsHandler',
    'GetPOSTransactionByIdQuery', 'GetPOSTransactionByIdHandler',
    'GetAllPOSTransactionsQuery', 'GetAllPOSTransactionsHandler',
    'GetWorkOrderByIdQuery', 'GetWorkOrderByIdHandler',
    'GetAllWorkOrdersQuery', 'GetAllWorkOrdersHandler',
    'GetWorkOrderTaskByIdQuery', 'GetWorkOrderTaskByIdHandler',
    'GetAllWorkOrderTasksQuery', 'GetAllWorkOrderTasksHandler',
    'GetProductionPlanByIdQuery', 'GetProductionPlanByIdHandler',
    'GetAllProductionPlansQuery', 'GetAllProductionPlansHandler',
    'GetProductionStepByIdQuery', 'GetProductionStepByIdHandler',
    'GetAllProductionStepsQuery', 'GetAllProductionStepsHandler',
    'GetProductionScheduleByIdQuery', 'GetProductionScheduleByIdHandler',
    'GetAllProductionSchedulesQuery', 'GetAllProductionSchedulesHandler',
    'GetEventByIdQuery', 'GetEventByIdHandler',
    'GetAllEventsQuery', 'GetAllEventsHandler',
    'GetQualityCheckByIdQuery', 'GetQualityCheckByIdHandler',
    'GetAllQualityChecksQuery', 'GetAllQualityChecksHandler',
    'GetQualityInspectionByIdQuery', 'GetQualityInspectionByIdHandler',
    'GetAllQualityInspectionsQuery', 'GetAllQualityInspectionsHandler',
    'GetQualityDefectByIdQuery', 'GetQualityDefectByIdHandler',
    'GetAllQualityDefectsQuery', 'GetAllQualityDefectsHandler',
    'GetQualityReportByIdQuery', 'GetQualityReportByIdHandler',
    'GetAllQualityReportsQuery', 'GetAllQualityReportsHandler',
    'GetMaintenanceScheduleByIdQuery', 'GetMaintenanceScheduleByIdHandler',
    'GetAllMaintenanceSchedulesQuery', 'GetAllMaintenanceSchedulesHandler',
    'GetMaintenanceWorkOrderByIdQuery', 'GetMaintenanceWorkOrderByIdHandler',
    'GetAllMaintenanceWorkOrdersQuery', 'GetAllMaintenanceWorkOrdersHandler',
    'GetEquipmentByIdQuery', 'GetEquipmentByIdHandler',
    'GetAllEquipmentsQuery', 'GetAllEquipmentsHandler',
    'GetMaintenanceReportByIdQuery', 'GetMaintenanceReportByIdHandler',
    'GetAllMaintenanceReportsQuery', 'GetAllMaintenanceReportsHandler',
    'GetInvestmentByIdQuery', 'GetInvestmentByIdHandler',
    'GetAllInvestmentsQuery', 'GetAllInvestmentsHandler',
    'GetEquipmentInvestmentByIdQuery', 'GetEquipmentInvestmentByIdHandler',
    'GetAllEquipmentInvestmentsQuery', 'GetAllEquipmentInvestmentsHandler',
    'GetInvestmentTransactionByIdQuery', 'GetInvestmentTransactionByIdHandler',
    'GetAllInvestmentTransactionsQuery', 'GetAllInvestmentTransactionsHandler',
    'GetRoleByIdQuery', 'GetRoleByIdHandler',
    'GetAllRolesQuery', 'GetAllRolesHandler',
    'GetTenantUserByIdQuery', 'GetTenantUserByIdHandler',
    'GetAllTenantUsersQuery', 'GetAllTenantUsersHandler',
    'GetNotificationByIdQuery', 'GetNotificationByIdHandler',
    'GetAllNotificationsQuery', 'GetAllNotificationsHandler',
    'GetNotificationPreferenceByIdQuery', 'GetNotificationPreferenceByIdHandler',
    'GetAllNotificationPreferencesQuery', 'GetAllNotificationPreferencesHandler',
    'GetInvoiceCustomizationByIdQuery', 'GetInvoiceCustomizationByIdHandler',
    'GetAllInvoiceCustomizationsQuery', 'GetAllInvoiceCustomizationsHandler',
]
'''
    
    with open(init_file, 'w', encoding='utf-8') as f:
        f.write(content)

def main():
    """Update main __init__.py files"""
    print("Updating main __init__.py files...")
    update_main_commands_init()
    print("  Updated commands/__init__.py")
    update_main_queries_init()
    print("  Updated queries/__init__.py")
    print("Done!")

if __name__ == '__main__':
    main()

