services:
  - type: web
    name: biztrack-api
    runtime: docker
    repo: https://github.com/sameerwork243-droid/Biztrack1
    rootDir: backend
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: FRONTEND_URL
        sync: false
      - key: INVOICE_SHARE_BASE_URL
        sync: false
      - key: INVOICE_SHARE_EXPIRE_DAYS
        value: "90"
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_MODE
        value: sandbox
      - key: PAYPAL_CURRENCY
        value: USD
      - key: PAYPAL_WEBHOOK_ID
        sync: false
