import uuid
from datetime import datetime

from sqlalchemy import JSON, Boolean, Column, DateTime, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from ...config.database_config import Base


class Tenant(Base):
    __tablename__ = "tenants"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    name = Column(String, nullable=False)
    domain = Column(String, unique=True, index=True)
    description = Column(Text)
    logo_url = Column(String, nullable=True)
    settings = Column(JSON, default={})
    isActive = Column(Boolean, default=True)
    createdAt = Column(DateTime, default=datetime.utcnow)
    updatedAt = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    users = relationship("User", back_populates="tenant")
    projects = relationship("Project", back_populates="tenant")
    subscriptions = relationship("Subscription", back_populates="tenant")
    tenant_users = relationship("TenantUser", back_populates="tenant")
    roles = relationship("Role", back_populates="tenant")
    quotes = relationship("Quote", back_populates="tenant")
    contracts = relationship("Contract", back_populates="tenant")
    leads = relationship("Lead", back_populates="tenant")
    contacts = relationship("Contact", back_populates="tenant")
    companies = relationship("Company", back_populates="tenant")
    opportunities = relationship("Opportunity", back_populates="tenant")
    sales_activities = relationship("SalesActivity", back_populates="tenant")
    customers = relationship("Customer", back_populates="tenant")
    products = relationship("Product", back_populates="tenant")
    warehouses = relationship("Warehouse", back_populates="tenant")
    suppliers = relationship("Supplier", back_populates="tenant")
    purchase_orders = relationship("PurchaseOrder", back_populates="tenant")
    receiving = relationship("Receiving", back_populates="tenant")
    storage_locations = relationship("StorageLocation", back_populates="tenant")
    stock_movements = relationship("StockMovement", back_populates="tenant")
    invoices = relationship("Invoice", back_populates="tenant")
    payments = relationship("Payment", back_populates="tenant")
    pos_shifts = relationship("POSShift", back_populates="tenant")
    pos_transactions = relationship("POSTransaction", back_populates="tenant")
    employees = relationship("Employee", back_populates="tenant")
    job_postings = relationship("JobPosting", back_populates="tenant")
    performance_reviews = relationship("PerformanceReview", back_populates="tenant")
    time_entries = relationship("TimeEntry", back_populates="tenant")
    leave_requests = relationship("LeaveRequest", back_populates="tenant")
    payroll = relationship("Payroll", back_populates="tenant")
    benefits = relationship("Benefits", back_populates="tenant")
    training = relationship("Training", back_populates="tenant")
    training_enrollments = relationship("TrainingEnrollment", back_populates="tenant")
    applications = relationship("Application", back_populates="tenant")
    customEventTypes = relationship("CustomEventType", back_populates="tenant")
    events = relationship("Event", back_populates="tenant")
    work_orders = relationship("WorkOrder", back_populates="tenant")
    production_plans = relationship("ProductionPlan", back_populates="tenant")
    production_schedules = relationship("ProductionSchedule", back_populates="tenant")
    chart_of_accounts = relationship("ChartOfAccounts", back_populates="tenant")
    ledger_transactions = relationship("LedgerTransaction", back_populates="tenant")
    journal_entries = relationship("JournalEntry", back_populates="tenant")
    financial_periods = relationship("FinancialPeriod", back_populates="tenant")
    budgets = relationship("Budget", back_populates="tenant")
    bank_accounts = relationship("BankAccount", back_populates="tenant")
    bank_transactions = relationship("BankTransaction", back_populates="tenant")
    cash_positions = relationship("CashPosition", back_populates="tenant")
    tills = relationship("Till", back_populates="tenant")
    till_transactions = relationship("TillTransaction", back_populates="tenant")
    customDepartments = relationship("CustomDepartment", back_populates="tenant")
    customLeaveTypes = relationship("CustomLeaveType", back_populates="tenant")
    customLeadSources = relationship("CustomLeadSource", back_populates="tenant")
    customContactSources = relationship("CustomContactSource", back_populates="tenant")
    customCompanyIndustries = relationship("CustomCompanyIndustry", back_populates="tenant")
    customContactTypes = relationship("CustomContactType", back_populates="tenant")
    customIndustries = relationship("CustomIndustry", back_populates="tenant")
    quality_checks = relationship("QualityCheck", back_populates="tenant")
    quality_inspections = relationship("QualityInspection", back_populates="tenant")
    quality_defects = relationship("QualityDefect", back_populates="tenant")
    quality_reports = relationship("QualityReport", back_populates="tenant")
    maintenance_schedules = relationship("MaintenanceSchedule", back_populates="tenant")
    maintenance_work_orders = relationship("MaintenanceWorkOrder", back_populates="tenant")
    maintenance_reports = relationship("MaintenanceReport", back_populates="tenant")
    equipment = relationship("Equipment", back_populates="tenant")
    invoice_customizations = relationship("InvoiceCustomization", back_populates="tenant")
    investments = relationship("Investment", back_populates="tenant")
    equipment_investments = relationship("EquipmentInvestment", back_populates="tenant")
    investment_transactions = relationship("InvestmentTransaction", back_populates="tenant")
    account_receivables = relationship("AccountReceivable", back_populates="tenant")
