import {
  LayoutDashboard,
  FolderOpen,
  CheckSquare,
  Users,
  Clock,
  BarChart3,
  UserCheck,
  Building,
  Calendar,
  TrendingUp,
  Target,
  FileText,
  DollarSign,
  Briefcase,
  Award,
  GraduationCap,
  Clock3,
  CreditCard,
  FileCheck,
  Banknote,
  BookOpen,
  Package,
  Receipt,
  Plus,
  Warehouse,
  MapPin,
  Truck,
  ClipboardList,
  PackageCheck,
  AlertTriangle,
  Factory,
  Wrench,
  Building2,
  Settings,
  Trash2,
  ArrowLeft,
  CheckCircle,
  ArrowRight,
  Bell,
  Car,
  HeartHandshake,
  CircleDollarSign,
  HelpingHand,
  Landmark,
  Contact,
  Sparkles,
  Gift,
} from 'lucide-react';
import type { MenuItem } from '@/src/types/sidebar';

export const allMenuItems: MenuItem[] = [
  {
    text: 'Dashboard',
    icon: LayoutDashboard,
    path: '/dashboard',
    roles: ['*'],
    planTypes: ['*'],
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    text: 'Donor Management',
    icon: Users,
    roles: ['*'],
    planTypes: ['ngo'],
    gradient: 'from-emerald-500 to-teal-500',
    subItems: [
      {
        text: 'Donor Dashboard',
        icon: LayoutDashboard,
        path: '/ngo/donor-dashboard',
        roles: ['*'],
        planTypes: ['ngo'],
      },
      {
        text: 'All Donors',
        icon: Users,
        path: '/ngo/donors',
        roles: ['*'],
        planTypes: ['ngo'],
      },
      {
        text: 'Partner Organizations',
        icon: Building,
        path: '/ngo/partner-organizations',
        roles: ['*'],
        planTypes: ['ngo'],
      },
      {
        text: 'Donor Leads',
        icon: Target,
        path: '/ngo/donor-leads',
        roles: ['*'],
        planTypes: ['ngo'],
      },
      {
        text: 'Gift Opportunities',
        icon: Sparkles,
        path: '/ngo/gift-opportunities',
        roles: ['*'],
        planTypes: ['ngo'],
      },
    ],
  },
  {
    text: 'Donation Management',
    icon: HeartHandshake,
    roles: ['*'],
    planTypes: ['ngo'],
    gradient: 'from-emerald-500 to-green-500',
    subItems: [
      {
        text: 'Donation Receipts',
        icon: Receipt,
        path: '/ngo/donation-receipts',
        roles: ['*'],
        planTypes: ['ngo'],
      },
      {
        text: 'Contribution Agreements',
        icon: FileCheck,
        path: '/ngo/contribution-agreements',
        roles: ['*'],
        planTypes: ['ngo'],
      },
      {
        text: 'Donation Installments',
        icon: Calendar,
        path: '/ngo/donation-installments',
        roles: ['*'],
        planTypes: ['ngo'],
      },
    ],
  },
  {
    text: 'Gift & Inventory',
    icon: Gift,
    roles: ['*'],
    planTypes: ['ngo'],
    gradient: 'from-violet-500 to-purple-500',
    subItems: [
      {
        text: 'Inventory Dashboard',
        icon: LayoutDashboard,
        path: '/ngo/inventory',
        roles: ['*'],
        planTypes: ['ngo'],
      },
      {
        text: 'Gift Items',
        icon: Package,
        path: '/ngo/gift-items',
        roles: ['*'],
        planTypes: ['ngo'],
      },
      {
        text: 'Stock Alerts',
        icon: AlertTriangle,
        path: '/ngo/stock-alerts',
        roles: ['*'],
        planTypes: ['ngo'],
      },
    ],
  },
  {
    text: 'Volunteer Management',
    icon: HelpingHand,
    roles: ['*'],
    planTypes: ['ngo'],
    gradient: 'from-teal-500 to-cyan-500',
    subItems: [
      {
        text: 'All Volunteers',
        icon: Users,
        path: '/ngo/volunteers',
        roles: ['*'],
        planTypes: ['ngo'],
      },
      {
        text: 'Leave Management',
        icon: Clock3,
        path: '/ngo/leave-management',
        roles: ['*'],
        planTypes: ['ngo'],
      },
    ],
  },
  {
    text: 'Relief Projects',
    icon: FolderOpen,
    roles: ['*'],
    planTypes: ['ngo'],
    gradient: 'from-blue-500 to-indigo-500',
    subItems: [
      {
        text: 'Active Projects',
        icon: Briefcase,
        path: '/ngo/relief-projects',
        roles: ['*'],
        planTypes: ['ngo'],
      },
      {
        text: 'Project Tasks',
        icon: CheckSquare,
        path: '/ngo/project-tasks',
        roles: ['*'],
        planTypes: ['ngo'],
      },
    ],
  },
  {
    text: 'Charity Reports',
    icon: BarChart3,
    path: '/ngo/reports',
    roles: ['*'],
    planTypes: ['ngo'],
    gradient: 'from-purple-500 to-violet-500',
  },
  {
    text: 'Charity Events',
    icon: Calendar,
    path: '/events',
    roles: ['*'],
    planTypes: ['ngo'],
    gradient: 'from-indigo-500 to-blue-500',
  },
  {
    text: 'Charity Banking',
    icon: Landmark,
    roles: ['*'],
    planTypes: ['ngo'],
    gradient: 'from-blue-500 to-indigo-500',
    subItems: [
      {
        text: 'Banking Dashboard',
        icon: LayoutDashboard,
        path: '/ngo/banking',
        roles: ['*'],
        planTypes: ['ngo'],
      },
      {
        text: 'Donation Transactions',
        icon: Receipt,
        path: '/ngo/donation-transactions',
        roles: ['*'],
        planTypes: ['ngo'],
      },
    ],
  },
  {
    text: 'Fund Accounting',
    icon: BookOpen,
    roles: ['*'],
    planTypes: ['ngo'],
    gradient: 'from-emerald-500 to-teal-500',
    subItems: [
      {
        text: 'Ledger Dashboard',
        icon: LayoutDashboard,
        path: '/ngo/ledger',
        roles: ['*'],
        planTypes: ['ngo'],
      },
      {
        text: 'Zakat Funds',
        icon: CircleDollarSign,
        path: '/ngo/zakat-funds',
        roles: ['*'],
        planTypes: ['ngo'],
      },
    ],
  },
  {
    text: 'Healthcare',
    icon: Building2,
    roles: ['*'],
    planTypes: ['healthcare'],
    gradient: 'from-teal-500 to-cyan-500',
    subItems: [
      {
        text: 'Appointments',
        icon: Calendar,
        path: '/healthcare/appointments',
        roles: ['*'],
        planTypes: ['healthcare'],
      },
      {
        text: 'Patients',
        icon: Users,
        path: '/healthcare/patients',
        roles: ['*'],
        planTypes: ['healthcare'],
      },
      {
        text: 'Staff',
        icon: Users,
        path: '/healthcare/staff',
        roles: ['*'],
        planTypes: ['healthcare'],
      },
      {
        text: 'Doctors',
        icon: UserCheck,
        path: '/healthcare/doctors',
        roles: ['*'],
        planTypes: ['healthcare'],
      },
      {
        text: 'Calendar',
        icon: Calendar,
        path: '/healthcare/calendar',
        roles: ['*'],
        planTypes: ['healthcare'],
      },
      {
        text: 'Patient History',
        icon: FileText,
        path: '/healthcare/patient-history',
        roles: ['*'],
        planTypes: ['healthcare'],
      },
      {
        text: 'Hospital Admitted Patients',
        icon: Building2,
        path: '/healthcare/admitted-patients',
        roles: ['*'],
        planTypes: ['healthcare'],
      },
      {
        text: 'Hospital Payments',
        icon: Banknote,
        path: '/healthcare/payments',
        roles: ['*'],
        planTypes: ['healthcare'],
      },
      {
        text: 'Daily Expense',
        icon: Receipt,
        path: '/healthcare/daily-expense',
        roles: ['*'],
        planTypes: ['healthcare'],
      },
    ],
  },
  {
    text: 'CRM',
    icon: Users,
    roles: ['*'],
    planTypes: ['commerce', 'agency', 'healthcare'],
    gradient: 'from-blue-500 to-indigo-500',
    subItems: [
      {
        text: 'Dashboard',
        icon: LayoutDashboard,
        path: '/crm',
        roles: ['*'],
        planTypes: ['commerce', 'agency', 'healthcare'],
      },
      {
        text: 'Customers',
        icon: Users,
        path: '/crm/customers',
        roles: ['*'],
        planTypes: ['commerce', 'agency', 'healthcare'],
      },
      {
        text: 'Companies',
        icon: Building,
        path: '/crm/companies',
        roles: ['*'],
        planTypes: ['commerce', 'agency', 'healthcare'],
      },
      {
        text: 'Contacts',
        icon: Users,
        path: '/crm/contacts',
        roles: ['*'],
        planTypes: ['commerce', 'agency', 'healthcare'],
      },
      {
        text: 'Leads',
        icon: Target,
        path: '/crm/leads',
        roles: ['*'],
        planTypes: ['commerce', 'agency', 'healthcare'],
      },
      {
        text: 'Opportunities',
        icon: TrendingUp,
        path: '/crm/opportunities',
        roles: ['*'],
        planTypes: ['commerce', 'agency', 'healthcare'],
      },
    ],
  },
  {
    text: 'Customers',
    icon: Users,
    path: '/workshop-management/customers',
    roles: ['*'],
    planTypes: ['workshop'],
    gradient: 'from-blue-500 to-indigo-500',
  },
  {
    text: 'Invoicing',
    icon: Banknote,
    path: '/invoices',
    roles: ['*'],
    planTypes: ['workshop', 'healthcare'],
    gradient: 'from-green-500 to-emerald-500',
  },
  {
    text: 'Sales',
    icon: DollarSign,
    roles: ['*'],
    planTypes: ['commerce', 'agency'],
    gradient: 'from-green-500 to-emerald-500',
    subItems: [
      {
        text: 'Quotes',
        icon: FileText,
        path: '/sales/quotes',
        roles: ['*'],
        planTypes: ['commerce', 'agency'],
      },
      {
        text: 'Contracts',
        icon: FileCheck,
        path: '/sales/contracts',
        roles: ['*'],
        planTypes: ['commerce', 'agency'],
      },
      {
        text: 'Analytics',
        icon: BarChart3,
        path: '/sales/analytics',
        roles: ['*'],
        planTypes: ['commerce', 'agency'],
      },
      {
        text: 'Invoices',
        icon: Banknote,
        path: '/sales/invoices',
        roles: ['*'],
        planTypes: ['commerce', 'agency'],
      },
      {
        text: 'Invoice Dashboard',
        icon: LayoutDashboard,
        path: '/sales/invoice-dashboard',
        roles: ['*'],
        planTypes: ['commerce', 'agency'],
      },
      {
        text: 'Installments',
        icon: Calendar,
        path: '/sales/installments',
        roles: ['*'],
        planTypes: ['commerce', 'agency'],
      },
      {
        text: 'Delivery Notes',
        icon: Truck,
        path: '/sales/delivery-notes',
        roles: ['*'],
        planTypes: ['commerce', 'agency'],
      },
    ],
  },
  {
    text: 'POS',
    icon: Banknote,
    roles: ['*'],
    planTypes: ['commerce', 'agency'],
    gradient: 'from-yellow-500 to-orange-500',
    subItems: [
      {
        text: 'Dashboard',
        icon: LayoutDashboard,
        path: '/pos',
        roles: ['*'],
        planTypes: ['commerce', 'agency'],
      },
      {
        text: 'New Sale',
        icon: Plus,
        path: '/pos/sale',
        roles: ['*'],
        planTypes: ['commerce', 'agency'],
      },
      {
        text: 'Products',
        icon: Package,
        path: '/pos/products',
        roles: ['*'],
        planTypes: ['commerce', 'agency'],
      },
      {
        text: 'Transactions',
        icon: Receipt,
        path: '/pos/transactions',
        roles: ['*'],
        planTypes: ['commerce', 'agency'],
      },
      {
        text: 'Shifts',
        icon: Clock3,
        path: '/pos/shifts',
        roles: ['*'],
        planTypes: ['commerce', 'agency'],
      },
      {
        text: 'Reports',
        icon: BarChart3,
        path: '/pos/reports',
        roles: ['*'],
        planTypes: ['commerce', 'agency'],
      },
    ],
  },
  {
    text: 'Inventory',
    icon: Warehouse,
    roles: ['*'],
    planTypes: ['*'], // Available for all plans
    gradient: 'from-teal-500 to-green-500',
    subItems: [
      {
        text: 'Dashboard',
        icon: LayoutDashboard,
        path: '/inventory',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Warehouses',
        icon: Warehouse,
        path: '/inventory/warehouses',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Storage Locations',
        icon: MapPin,
        path: '/inventory/storage-locations',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Stock Movements',
        icon: Truck,
        path: '/inventory/stock-movements',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Purchase Orders',
        icon: ClipboardList,
        path: '/inventory/purchase-orders',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Receiving',
        icon: PackageCheck,
        path: '/inventory/receiving',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Products',
        icon: Package,
        path: '/inventory/products',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Stock Alerts',
        icon: AlertTriangle,
        path: '/inventory/alerts',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Dumps',
        icon: Trash2,
        path: '/inventory/dumps',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Return from Customer',
        icon: ArrowLeft,
        path: '/inventory/customer-returns',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Return to Supplier',
        icon: ArrowRight,
        path: '/inventory/supplier-returns',
        roles: ['*'],
        planTypes: ['*'],
      },
    ],
  },
  {
    text: 'HRM',
    icon: UserCheck,
    roles: ['*'],
    planTypes: ['*'],
    gradient: 'from-purple-500 to-pink-500',
    subItems: [
      {
        text: 'Dashboard',
        icon: LayoutDashboard,
        path: '/hrm',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Employees',
        icon: Users,
        path: '/hrm/employees',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Job Postings',
        icon: Briefcase,
        path: '/hrm/job-postings',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Performance Reviews',
        icon: Award,
        path: '/hrm/performance-reviews',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Leave Management',
        icon: Calendar,
        path: '/hrm/leave-management',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Training',
        icon: GraduationCap,
        path: '/hrm/training',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Payroll',
        icon: Banknote,
        path: '/hrm/payroll',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Suppliers',
        icon: Building,
        path: '/hrm/suppliers',
        roles: ['*'],
        planTypes: ['*'],
      },
    ],
  },
  {
    text: 'Project Management',
    icon: FolderOpen,
    roles: ['*'],
    planTypes: ['*'], // Available for all plans
    gradient: 'from-orange-500 to-red-500',
    subItems: [
      {
        text: 'Projects',
        icon: FolderOpen,
        path: '/projects',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Tasks',
        icon: CheckSquare,
        path: '/tasks',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Team Members',
        icon: Users,
        path: '/team',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Time Tracking',
        icon: Clock,
        path: '/time-tracking',
        roles: ['*'],
        planTypes: ['*'],
      },
    ],
  },
  {
    text: 'Reports',
    icon: BarChart3,
    path: '/reports',
    roles: ['*'],
    planTypes: ['*'],
    gradient: 'from-purple-500 to-violet-500',
  },
  {
    text: 'Events',
    icon: Calendar,
    path: '/events',
    roles: ['*'],
    planTypes: ['*'], 
    gradient: 'from-indigo-500 to-blue-500',
  },
  // Workshop-specific modules
  {
    text: 'Workshop Management',
    icon: Factory,
    roles: ['*'],
    planTypes: ['workshop'], // Workshop focused
    gradient: 'from-orange-500 to-red-500',
    subItems: [
      {
        text: 'Work Orders',
        icon: Wrench,
        path: '/workshop-management/work-orders',
        roles: ['*'],
        planTypes: ['workshop'],
      },
      {
        text: 'Job Cards',
        icon: ClipboardList,
        path: '/workshop-management/job-cards',
        roles: ['*'],
        planTypes: ['workshop'],
      },
      {
        text: 'Vehicles',
        icon: Car,
        path: '/workshop-management/vehicles',
        roles: ['*'],
        planTypes: ['workshop'],
      },
      {
        text: 'Production Planning',
        icon: Factory,
        path: '/workshop-management/production',
        roles: ['*'],
        planTypes: ['workshop'],
      },
      {
        text: 'Quality Control',
        icon: CheckSquare,
        path: '/workshop-management/quality-control',
        roles: ['*'],
        planTypes: ['workshop'],
      },
      {
        text: 'Equipment Maintenance',
        icon: Wrench,
        path: '/workshop-management/maintenance',
        roles: ['*'],
        planTypes: ['workshop'],
      },
    ],
  },
  // Banking - Available for all plan types
  {
    text: 'Banking',
    icon: Banknote,
    roles: ['*'],
    planTypes: ['*'], // Available for all plans
    gradient: 'from-blue-500 to-indigo-500',
    subItems: [
      {
        text: 'Dashboard',
        icon: LayoutDashboard,
        path: '/banking',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Bank Accounts',
        icon: CreditCard,
        path: '/banking/accounts',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Transactions',
        icon: Receipt,
        path: '/banking/transactions',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Reconciliation',
        icon: CheckCircle,
        path: '/banking/reconciliation',
        roles: ['*'],
        planTypes: ['*'],
      },
    ],
  },
  // Ledger - Available for all plan types
  {
    text: 'Financial Ledger',
    icon: BookOpen,
    roles: ['*'],
    planTypes: ['*'], // Available for all plans
    gradient: 'from-emerald-500 to-teal-500',
    subItems: [
      {
        text: 'Dashboard',
        icon: LayoutDashboard,
        path: '/ledger',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Profit & Loss',
        icon: TrendingUp,
        path: '/ledger/profit-loss',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Investments',
        icon: DollarSign,
        path: '/ledger/investments',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Transactions',
        icon: Receipt,
        path: '/ledger/transactions',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Credit book (Account Receivable)',
        icon: FileText,
        path: '/ledger/account-receivables',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Reports',
        icon: BarChart3,
        path: '/ledger/reports',
        roles: ['*'],
        planTypes: ['*'],
      },
    ],
  },
  // Settings - Available for all plan types
  {
    text: 'Settings',
    icon: Settings,
    roles: ['*'],
    planTypes: ['*'], // Available for all plans
    gradient: 'from-gray-500 to-slate-500',
    subItems: [
      {
        text: 'General Settings',
        icon: Settings,
        path: '/settings',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Notifications',
        icon: Bell,
        path: '/notifications',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Notification Settings',
        icon: Settings,
        path: '/notifications/settings',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Subscription',
        icon: CreditCard,
        path: '/subscription/manage',
        roles: ['owner', 'admin'],
        planTypes: ['*'],
      },
    ],
  },
  {
    text: 'User Management',
    icon: UserCheck,
    path: '/users',
    roles: ['owner', 'admin'],
    planTypes: ['*'],
    gradient: 'from-purple-500 to-violet-500',
  },
];

// Super admin menu items - only show Tenants, Plans, and Subscriptions
export const superAdminMenuItems: MenuItem[] = [
  {
    text: 'Tenants',
    icon: Building2,
    path: '/admin/tenants',
    roles: ['super_admin'],
    planTypes: ['*'],
    gradient: 'from-purple-500 to-indigo-500',
  },
  {
    text: 'Plans',
    icon: CreditCard,
    path: '/admin/plans',
    roles: ['super_admin'],
    planTypes: ['*'],
    gradient: 'from-green-500 to-emerald-500',
  },
  {
    text: 'Subscriptions',
    icon: CreditCard,
    path: '/admin/subscriptions',
    roles: ['super_admin'],
    planTypes: ['*'],
    gradient: 'from-blue-500 to-cyan-500',
  },
];


