import {
  LayoutDashboard,
  FolderOpen,
  CheckSquare,
  Users,
  Clock,
  BarChart3,
  UserCheck,
  UserCircle,
  Building,
  Calendar,
  TrendingUp,
  Target,
  FileText,
  DollarSign,
  Briefcase,
  Award,
  GraduationCap,
  CreditCard,
  FileCheck,
  Banknote,
  BookOpen,
  Package,
  Warehouse,
  MapPin,
  Truck,
  ClipboardList,
  PackageCheck,
  AlertTriangle,
  Settings,
  Trash2,
  ArrowLeft,
  CheckCircle,
  ArrowRight,
  Bell,
  Building2,
  Receipt,
} from 'lucide-react';
import type { MenuItem } from '@/src/types/sidebar';

export const allMenuItems: MenuItem[] = [
  {
    text: 'Dashboard',
    icon: LayoutDashboard,
    path: '/dashboard',
    roles: ['*'],
    planTypes: ['*'],
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    text: 'CRM',
    icon: Users,
    roles: ['*'],
    planTypes: ['agency'],
    gradient: 'from-blue-500 to-indigo-500',
    subItems: [
      {
        text: 'Dashboard',
        icon: LayoutDashboard,
        path: '/crm',
        roles: ['*'],
        planTypes: ['agency'],
      },
      {
        text: 'Customers',
        icon: Users,
        path: '/crm/customers',
        roles: ['*'],
        planTypes: ['agency'],
      },
      {
        text: 'Companies',
        icon: Building,
        path: '/crm/companies',
        roles: ['*'],
        planTypes: ['agency'],
      },
      {
        text: 'Contacts',
        icon: Users,
        path: '/crm/contacts',
        roles: ['*'],
        planTypes: ['agency'],
      },
      {
        text: 'Leads',
        icon: Target,
        path: '/crm/leads',
        roles: ['*'],
        planTypes: ['agency'],
      },
      {
        text: 'Opportunities',
        icon: TrendingUp,
        path: '/crm/opportunities',
        roles: ['*'],
        planTypes: ['agency'],
      },
      {
        text: 'Agent Portal',
        icon: Award,
        path: '/crm/agent-portal',
        roles: ['*'],
        planTypes: ['agency'],
      },
    ],
  },
  {
    text: 'Sales',
    icon: DollarSign,
    roles: ['*'],
    planTypes: ['agency'],
    gradient: 'from-green-500 to-emerald-500',
    subItems: [
      {
        text: 'Quotes',
        icon: FileText,
        path: '/sales/quotes',
        roles: ['*'],
        planTypes: ['agency'],
      },
      {
        text: 'Contracts',
        icon: FileCheck,
        path: '/sales/contracts',
        roles: ['*'],
        planTypes: ['agency'],
      },
      {
        text: 'Analytics',
        icon: BarChart3,
        path: '/sales/analytics',
        roles: ['*'],
        planTypes: ['agency'],
      },
      {
        text: 'Create Invoice',
        icon: Banknote,
        path: '/sales/invoices',
        roles: ['*'],
        planTypes: ['agency'],
      },
      {
        text: 'Invoice Dashboard',
        icon: LayoutDashboard,
        path: '/sales/invoice-dashboard',
        roles: ['*'],
        planTypes: ['agency'],
      },
      {
        text: 'Installments',
        icon: Calendar,
        path: '/sales/installments',
        roles: ['*'],
        planTypes: ['agency'],
      },
      {
        text: 'Delivery Notes',
        icon: Truck,
        path: '/sales/delivery-notes',
        roles: ['*'],
        planTypes: ['agency'],
      },
    ],
  },
  {
    text: 'Inventory',
    icon: Warehouse,
    roles: ['*'],
    planTypes: ['*'], // Available for all plans
    gradient: 'from-teal-500 to-green-500',
    subItems: [
      {
        text: 'Dashboard',
        icon: LayoutDashboard,
        path: '/inventory',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Warehouses',
        icon: Warehouse,
        path: '/inventory/warehouses',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Storage Locations',
        icon: MapPin,
        path: '/inventory/storage-locations',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Stock Movements',
        icon: Truck,
        path: '/inventory/stock-movements',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Purchase Orders',
        icon: ClipboardList,
        path: '/inventory/purchase-orders',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Receiving',
        icon: PackageCheck,
        path: '/inventory/receiving',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Products',
        icon: Package,
        path: '/inventory/products',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Stock Alerts',
        icon: AlertTriangle,
        path: '/inventory/alerts',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Dumps',
        icon: Trash2,
        path: '/inventory/dumps',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Return from Customer',
        icon: ArrowLeft,
        path: '/inventory/customer-returns',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Return to Supplier',
        icon: ArrowRight,
        path: '/inventory/supplier-returns',
        roles: ['*'],
        planTypes: ['*'],
      },
    ],
  },
  {
    text: 'My Work',
    icon: UserCircle,
    roles: ['*'],
    planTypes: ['agency'],
    gradient: 'from-indigo-500 to-violet-500',
    subItems: [
      {
        text: 'My Profile',
        icon: UserCircle,
        path: '/employee-portal/profile',
        roles: ['*'],
        planTypes: ['agency'],
      },
      {
        text: 'Time Tracking',
        icon: Clock,
        path: '/employee-portal/time',
        roles: ['*'],
        planTypes: ['agency'],
      },
    ],
  },
  {
    text: 'HRM',
    icon: UserCheck,
    roles: ['*'],
    planTypes: ['*'],
    gradient: 'from-purple-500 to-pink-500',
    subItems: [
      {
        text: 'Dashboard',
        icon: LayoutDashboard,
        path: '/hrm',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Employees',
        icon: Users,
        path: '/hrm/employees',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Job Postings',
        icon: Briefcase,
        path: '/hrm/job-postings',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Performance Reviews',
        icon: Award,
        path: '/hrm/performance-reviews',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Leave Management',
        icon: Calendar,
        path: '/hrm/leave-management',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Training',
        icon: GraduationCap,
        path: '/hrm/training',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Payroll',
        icon: Banknote,
        path: '/hrm/payroll',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Suppliers',
        icon: Building,
        path: '/hrm/suppliers',
        roles: ['*'],
        planTypes: ['*'],
      },
    ],
  },
  {
    text: 'Project Management',
    icon: FolderOpen,
    roles: ['*'],
    planTypes: ['*'], // Available for all plans
    gradient: 'from-orange-500 to-red-500',
    subItems: [
      {
        text: 'Projects',
        icon: FolderOpen,
        path: '/projects',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Tasks',
        icon: CheckSquare,
        path: '/tasks',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Team Members',
        icon: Users,
        path: '/team',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Time Tracking',
        icon: Clock,
        path: '/time-tracking',
        roles: ['*'],
        planTypes: ['*'],
      },
    ],
  },
  {
    text: 'Reports',
    icon: BarChart3,
    path: '/reports',
    roles: ['*'],
    planTypes: ['*'],
    gradient: 'from-purple-500 to-violet-500',
  },
  {
    text: 'Events',
    icon: Calendar,
    path: '/events',
    roles: ['*'],
    planTypes: ['*'],
    gradient: 'from-indigo-500 to-blue-500',
  },
  // Banking - Available for all plan types
  {
    text: 'Banking',
    icon: Banknote,
    roles: ['*'],
    planTypes: ['*'], // Available for all plans
    gradient: 'from-blue-500 to-indigo-500',
    subItems: [
      {
        text: 'Dashboard',
        icon: LayoutDashboard,
        path: '/banking',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Bank Accounts',
        icon: CreditCard,
        path: '/banking/accounts',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Transactions',
        icon: Receipt,
        path: '/banking/transactions',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Reconciliation',
        icon: CheckCircle,
        path: '/banking/reconciliation',
        roles: ['*'],
        planTypes: ['*'],
      },
    ],
  },
  // Ledger - Available for all plan types
  {
    text: 'Financial Ledger',
    icon: BookOpen,
    roles: ['*'],
    planTypes: ['*'], // Available for all plans
    gradient: 'from-emerald-500 to-teal-500',
    subItems: [
      {
        text: 'Dashboard',
        icon: LayoutDashboard,
        path: '/ledger',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Profit & Loss',
        icon: TrendingUp,
        path: '/ledger/profit-loss',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Investments',
        icon: DollarSign,
        path: '/ledger/investments',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Transactions',
        icon: Receipt,
        path: '/ledger/transactions',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Credit book (Account Receivable)',
        icon: FileText,
        path: '/ledger/account-receivables',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Reports',
        icon: BarChart3,
        path: '/ledger/reports',
        roles: ['*'],
        planTypes: ['*'],
      },
    ],
  },
  // Settings - Available for all plan types
  {
    text: 'Settings',
    icon: Settings,
    roles: ['*'],
    planTypes: ['*'], // Available for all plans
    gradient: 'from-gray-500 to-slate-500',
    subItems: [
      {
        text: 'General Settings',
        icon: Settings,
        path: '/settings',
        roles: ['owner', 'admin'],
        planTypes: ['*'],
      },
      {
        text: 'Notifications',
        icon: Bell,
        path: '/notifications',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Notification Settings',
        icon: Settings,
        path: '/notifications/settings',
        roles: ['*'],
        planTypes: ['*'],
      },
      {
        text: 'Subscription',
        icon: CreditCard,
        path: '/subscription/manage',
        roles: ['owner', 'admin'],
        planTypes: ['*'],
      },
    ],
  },
  {
    text: 'User Management',
    icon: UserCheck,
    path: '/users',
    roles: ['owner', 'admin'],
    planTypes: ['*'],
    gradient: 'from-purple-500 to-violet-500',
  },
];

export const superAdminMenuItems: MenuItem[] = [
  {
    text: 'Tenants',
    icon: Building2,
    path: '/admin/tenants',
    roles: ['super_admin'],
    planTypes: ['*'],
    gradient: 'from-purple-500 to-indigo-500',
  },
  {
    text: 'Plans',
    icon: CreditCard,
    path: '/admin/plans',
    roles: ['super_admin'],
    planTypes: ['*'],
    gradient: 'from-green-500 to-emerald-500',
  },
  {
    text: 'Subscriptions',
    icon: CreditCard,
    path: '/admin/subscriptions',
    roles: ['super_admin'],
    planTypes: ['*'],
    gradient: 'from-blue-500 to-cyan-500',
  },
];