"""initial_schema

Revision ID: a04b0737ff5c
Revises: 
Create Date: 2026-06-03 22:57:42.840747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a04b0737ff5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
